FROM node:lts-alpine as build-stage
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install pnpm -g
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]